namespace RPRSharp;

/// <summary>
/// rpr_curve_parameter
/// </summary>
public enum CurveParameter : int
{
    CONTROLPOINTS_COUNT = 0x830,
    CONTROLPOINTS_DATA = 0x831,
    CONTROLPOINTS_STRIDE = 0x832,
    INDICES_COUNT = 0x833,
    INDICES_DATA = 0x834,
    RADIUS = 0x835,
    UV = 0x836,
    COUNT_CURVE = 0x837,
    SEGMENTS_PER_CURVE = 0x838,
    CREATION_FLAG = 0x839,
    NAME = Rpr.ObjectName,
    UNIQUE_ID = Rpr.ObjectUniqueId,
    CUSTOM_PTR = Rpr.ObjectCustomPtr,
    TRANSFORM = ShapeInfo.TRANSFORM,
    MATERIAL = ShapeInfo.MATERIAL,
    VISIBILITY_PRIMARY_ONLY_FLAG = ShapeInfo.VISIBILITY_PRIMARY_ONLY_FLAG,
    VISIBILITY_SHADOW = ShapeInfo.VISIBILITY_SHADOW,
    VISIBILITY_REFLECTION = ShapeInfo.VISIBILITY_REFLECTION,
    VISIBILITY_REFRACTION = ShapeInfo.VISIBILITY_REFRACTION,
    VISIBILITY_TRANSPARENT = ShapeInfo.VISIBILITY_TRANSPARENT,
    VISIBILITY_DIFFUSE = ShapeInfo.VISIBILITY_DIFFUSE,
    VISIBILITY_GLOSSY_REFLECTION = ShapeInfo.VISIBILITY_GLOSSY_REFLECTION,
    VISIBILITY_GLOSSY_REFRACTION = ShapeInfo.VISIBILITY_GLOSSY_REFRACTION,
    VISIBILITY_LIGHT = ShapeInfo.VISIBILITY_LIGHT,
    VISIBILITY_RECEIVE_SHADOW = ShapeInfo.VISIBILITY_RECEIVE_SHADOW
}
