namespace RPRSharp;

/// <summary>
/// rpr_light_info
/// </summary>
public enum LightInfo : int
{
    TYPE = 0x801,
    TRANSFORM = 0x803,
    GROUP_ID = 0x805,
    RENDER_LAYER_LIST = 0x806,
    VISIBILITY_LIGHT = 0x807,
    NAME = Rpr.ObjectName,
    UNIQUE_ID = Rpr.ObjectUniqueId,
    CUSTOM_PTR = Rpr.ObjectCustomPtr,

    /* point light */
    POINT_LIGHT_RADIANT_POWER = 0x804,

    /* directional light */
    DIRECTIONAL_LIGHT_RADIANT_POWER = 0x808,
    DIRECTIONAL_LIGHT_SHADOW_SOFTNESS_ANGLE = 0x80A,

    /* spot light */
    SPOT_LIGHT_RADIANT_POWER = 0x80B,
    SPOT_LIGHT_CONE_SHAPE = 0x80C,
    SPOT_LIGHT_IMAGE = 0x80D,

    /* environment light */
    ENVIRONMENT_LIGHT_IMAGE = 0x80F,
    ENVIRONMENT_LIGHT_INTENSITY_SCALE = 0x810,
    ENVIRONMENT_LIGHT_PORTAL_LIST = 0x818,
    ENVIRONMENT_LIGHT_PORTAL_COUNT = 0x819,
    ENVIRONMENT_LIGHT_OVERRIDE_REFLECTION = 0x81A,
    ENVIRONMENT_LIGHT_OVERRIDE_REFRACTION = 0x81B,
    ENVIRONMENT_LIGHT_OVERRIDE_TRANSPARENCY = 0x81C,
    ENVIRONMENT_LIGHT_OVERRIDE_BACKGROUND = 0x81D,
    ENVIRONMENT_LIGHT_OVERRIDE_IRRADIANCE = 0x81E,

    /* sky light */
    SKY_LIGHT_TURBIDITY = 0x812,
    SKY_LIGHT_ALBEDO = 0x813,
    SKY_LIGHT_SCALE = 0x814,
    SKY_LIGHT_DIRECTION = 0x815,
    SKY_LIGHT_PORTAL_LIST = 0x820,
    SKY_LIGHT_PORTAL_COUNT = 0x821,

    /* IES light */
    IES_LIGHT_RADIANT_POWER = 0x816,
    IES_LIGHT_IMAGE_DESC = 0x817,

    /* sphere light */
    SPHERE_LIGHT_RADIANT_POWER = 0x822,
    SPHERE_LIGHT_RADIUS = 0x824,

    /* disk light */
    DISK_LIGHT_RADIANT_POWER = 0x823,
    DISK_LIGHT_RADIUS = 0x825,
    DISK_LIGHT_ANGLE = 0x826,
    DISK_LIGHT_INNER_ANGLE = 0x827
}
