namespace RPRSharp;

/// <summary>
/// rpr_status
/// </summary>
public enum Status : int
{
    SUCCESS = 0,
    ERROR_COMPUTE_API_NOT_SUPPORTED = -1,
    ERROR_OUT_OF_SYSTEM_MEMORY = -2,
    ERROR_OUT_OF_VIDEO_MEMORY = -3,
    ERROR_SHADER_COMPILATION = -4,
    ERROR_INVALID_LIGHTPATH_EXPR = -5,
    ERROR_INVALID_IMAGE = -6,
    ERROR_INVALID_AA_METHOD = -7,
    ERROR_UNSUPPORTED_IMAGE_FORMAT = -8,
    ERROR_INVALID_GL_TEXTURE = -9,
    ERROR_INVALID_CL_IMAGE = -10,
    ERROR_INVALID_OBJECT = -11,
    ERROR_INVALID_PARAMETER = -12,
    ERROR_INVALID_TAG = -13,
    ERROR_INVALID_LIGHT = -14,
    ERROR_INVALID_CONTEXT = -15,
    ERROR_UNIMPLEMENTED = -16,
    ERROR_INVALID_API_VERSION = -17,
    ERROR_INTERNAL_ERROR = -18,
    ERROR_IO_ERROR = -19,
    ERROR_UNSUPPORTED_SHADER_PARAMETER_TYPE = -20,
    ERROR_MATERIAL_STACK_OVERFLOW = -21,
    ERROR_INVALID_PARAMETER_TYPE = -22,
    ERROR_UNSUPPORTED = -23,
    ERROR_OPENCL_OUT_OF_HOST_MEMORY = -24,
    ERROR_OPENGL = -25,
    ERROR_OPENCL = -26,
    ERROR_NULLPTR = -27,
    ERROR_NODETYPE = -28,
    ERROR_ABORTED = -29
}
